#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/logs.sh"

##? Fetch logs of containers
##?
##? Usage:
##?     logs
##?
##? Examples:
##?     logs

sx::parse_arguments "${@}"

sx::docker::logs
