#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/ls.sh"

##? List objects
##?
##? Usage:
##?     ls [--ips]
##?
##? Options:
##?     --ips  Show only containers and their respective IPs
##?
##?
##? Examples:
##?     ls
##?     ls --ips

sx::parse_arguments "${@}"

sx::docker::objects "${ips:-}"
