#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_COMMAND_DIR}/.library/tmux/core.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/tmux.sh"

##? Create a new TMUX window with the given container details
##?
##? Usage:
##?     tmux
##?
##? Examples:
##?     tmux

sx::parse_arguments "${@}"

sx::docker::tmux
