#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/top.sh"

##? Display the running processes of a container
##?
##? Usage:
##?     top
##?
##? Examples:
##?     top

sx::parse_arguments "${@}"

sx::docker::top
