#!/usr/bin/env bash

# Get week number
alias week='date +%V'

# Reload the shell (i.e. invoke as a login shell)
alias reload='exec ${SHELL} -l'

# Rerun last command with sudo
alias please='sudo $(fc -ln -1)'

# Flush DNS
alias flush='sx system dns --flush'

# Clear trash
alias clear-trash='sx system clear-trash'

# Get current network interface or protocol statistics
alias traffic='netstat -w1'

# Speed Test: https://github.com/sivel/speedtest-cli
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'

# Enable simplealiases to be sudo'ed. ("sudone"?)
# http://www.gnu.org/software/bash/manual/bashref.html#Aliases says: "If the
# last character of the alias value is a space or tab character, then the next
# command word following the alias is also checked for alias expansion."
#
# Reference:
# https://github.com/janmoesen/tilde/commit/805e8117fd0fb429055d280509e14be8427c226b
alias sudo='sudo '
# Using the same approach to make watch work with aliases
alias watch='watch '

# Android
# shellcheck disable=SC2139  # This expands when defined, not when used
alias emu="${ANDROID_HOME}/tools/emulator"

# Docker Compose
alias dc='docker-compose'

# Docker
alias dd='sx docker delete'
alias ds='sx docker ls'
alias dl='sx docker logs'
alias di='sx docker inspect'
alias dex='sx docker exec'

# tmux
alias ts='sx terminal tmux ls'
alias tn='sx terminal tmux new'
alias ta='sx terminal tmux attach'
alias tk='sx terminal tmux kill'
alias tka='sx terminal tmux kill-all'
alias tfa='sx terminal tmux force-attach'

# OpenShift
alias op='sx openshift project'

# Clipboard
alias pbcopy='sx system clipboard copy'
alias pbpaste='sx system clipboard paste'

# NVM
# https://github.com/nvm-sh/nvm/issues/1277
alias load_nvm='NVM_ENABLED=true reload'

# Forgit
# https://github.com/wfxr/forgit
alias load_forgit='source <(curl -sSL git.io/forgit)'
