#!/usr/bin/env bash

alias dns='sx system dns --query'

alias cert='sx security certificate --get --host'
alias certsans='sx security certificate --sans --host'

alias public_ip='sx ip public'
alias private_ip='sx ip private'

function shinatra() {
  local -r func_name="${FUNCNAME[0]:-${funcstack[1]}}"
  local -r port="${1}"
  local -r response_body="${2}"

  if [ -z "${port}" ] || [ -z "${response_body}" ]; then
    echo '!!! This function needs a port and a response body as arguments' >&2
    echo "!!! e.g. ${func_name} 8080 OK" >&2
    return 1
  fi

  curl 'https://raw.githubusercontent.com/benrady/shinatra/master/shinatra.sh' \
    | bash -s -- "${1}" "${2}"
}

function akamai() {
  curl \
    -I \
    -H 'Pragma: akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-cache-key, akamai-x-get-extracted-values, akamai-x-get-nonces, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, akamai-x-serial-no' \
    "${@}"
}

# Reference: https://stackoverflow.com/a/22625150/3691240
function curltime() {
  local -r template="$(cat << EOF
\n
           Name lookup time: %{time_namelookup}\n
  Establish connection time: %{time_connect}\n
 SSL/SSH/etc handshake time: %{time_appconnect}\n
     Pre-file-transfer time: %{time_pretransfer}\n
              Redirect time: %{time_redirect}\n
         Time to first byte: %{time_starttransfer}\n
              HTTP/FTP Code: %{http_code}\n
                     -------\n
                 Total time: %{time_total}\n\n\n

Note: The times are displayed in seconds.\n
EOF
)"

  curl \
    --silent \
    --header "Authorization: Bearer ${TOKEN}" \
    --header "User-Agent: curltime/sphynx ($(uname))" \
    --write-out @- \
    --output /dev/null \
    "${@}" <<< "${template}"
}
