- name: Updating all applications
  community.general.mas:
    upgrade_all: true

- name: Installing applications
  community.general.mas:
    id: "{{ item }}"
    state: present
  loop: "{{ applications }}"
