confirm-before-quit = false
hide-mouse-cursor-when-typing = true

padding-x = 5
padding-y = [5, 5]

[keyboard]
disable-ctlseqs-alt = false

[cursor]
shape = 'underline'
blinking = false

[window]
mode = "maximized"
opacity = 0.6
blur = true
decorations = "Transparent"

[scroll]
multiplier = 5.0
divider = 1.0

[navigation]
mode = "Plain"
hide-if-single = true
use-current-path = true
use-split = false

[shell]
program = "/usr/local/bin/zsh"
args = [
  "--login",
  "--interactive",
  "-c",
  "sx terminal tmux force-attach 'sphynx'",
]

[bindings]
keys = [
  { key = "k", with = "super", action = "ClearHistory" },
]

[fonts]
size = 14
family = "Fira Code"

[fonts.regular]
family = "Fira Code"
style = "Normal"
weight = 500

[fonts.bold]
family = "Fira Code"
style = "Normal"
weight = 800

[fonts.italic]
family = "Fira Code"
style = "Italic"
weight = 500

[fonts.bold-italic]
family = "Fira Code"
style = "Italic"
weight = 800

[colors]
background = "#0b0b0d"
foreground = "#e5e5e5"
cursor = '#e5e5e5'

# Regular colors
black = "#191919"
blue = "#045b96"
cyan = "#28c3d4"
green = "#329932"
magenta = "#e500e5"
red = "#da1e37"
white = "#e5e5e5"
yellow = "#ffff00"

# Dim colors
dim-black = "#000000"
dim-blue = "#0f4c75"
dim-cyan = "#22b9ca"
dim-green = "#008000"
dim-magenta = "#cc00cc"
dim-red = "#b20000"
dim-white = "#cccccc"
dim-yellow = "#e5e500"

# Light colors
light-black = "#6c757d"
light-blue = "#3282b8"
light-cyan = "#3fc5f0"
light-green = "#66b266"
light-magenta = "#ff00ff"
light-red = "#f94144"
light-white = "#ffffff"
light-yellow = "#ffff66"
