dock_apps:
  - "/System/Applications/Mail.app"
  - "/System/Applications/Reminders.app"
  - "/Applications/Brave Browser.app"
  - "/Applications/Slack.app"
  - "/Applications/Telegram Lite.app"
  - "/Applications/WhatsApp.app"
  - "/Applications/Spotify.app"
  - "/System/Applications/Calendar.app"
  - "/Applications/GitHub Desktop.app"
  - "/Applications/Alacritty.app"
  - "/Applications/Obsidian.app"
