- name: Checking /usr/local/bin directory
  stat:
    path: "/usr/local/bin"
  register: local_bin

- name: Moving all /usr/local/bin content to /opt/homebrew/bin
  shell: "mv /usr/local/bin/* /opt/homebrew/bin/ || true"
  become: true
  when:
    - local_bin.stat.islnk is defined and not local_bin.stat.islnk
    - ansible_architecture == 'arm64'
    - ansible_os_family == 'Darwin'

- name: Creating symbolic link from /usr/local/bin to /opt/homebrew/bin
  file:
    src: "/opt/homebrew/bin"
    dest: "/usr/local/bin"
    state: link
    force: true
  become: true
  when:
    - local_bin.stat.islnk is defined and not local_bin.stat.islnk
    - ansible_architecture == 'arm64'
    - ansible_os_family == 'Darwin'

- name: Tapping repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ repositories }}"

- name: Updating Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Upgrading all formulas
  community.general.homebrew:
    upgrade_all: true

- name: Upgrading all casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Installing Homebrew formulas
  community.general.homebrew:
    name: "{{ formulas }}"
    state: present

- name: Installing Homebrew casks
  community.general.homebrew_cask:
    name: "{{ casks }}"
