#!/usr/bin/env bash

set -o errexit
set -o pipefail

if ${SPHYNX_DEBUG_COMPLETION:-false}; then
  set -x
fi

## Variables

# shellcheck disable=SC2153  # Possible Misspelling
export SPHYNX_COMMAND_DIR="${SPHYNX_DIR:-}/cli"

## Functions

function namespaces() {
  local -r filter="${1}"

  # shellcheck disable=SC2038  # Use -print0/-0 or find -exec + to allow for non-alphanumeric filenames
  find "${SPHYNX_COMMAND_DIR}" \
    -maxdepth 1 \
    ! -path "${SPHYNX_COMMAND_DIR}" \
    ! -path '*/.library*' \
    ! -path '*/.internal*' \
    -a -type d -a -name "${filter}*" \
    -o -type f -a -name "${filter}*" -a \( -perm -u=x -o -perm -g=x -o -perm -o=x \) \
    | xargs -I % basename %
}

function commands() {
  local -r namespace="${1}"

  # shellcheck disable=SC2038  # Use -print0/-0 or find -exec + to allow for non-alphanumeric filenames
  find "${namespace}" \
    -maxdepth 1 \
    -type f \
    \( -perm -u=x -o -perm -g=x -o -perm -o=x \) \
    | xargs -I % basename %
}

function main() {
  local -r current_word="${1}"
  local -r namespace_prefix="${3}"
  local -r command_prefix="${4}"
  local -r n_args="${#}"

  if [ "${n_args}" -eq 2 ]; then
    namespaces
    exit 0
  fi

  if [ "${n_args}" -eq 3 ]; then
    local namespaces=()
    while IFS='' read -r line; do namespaces+=("${line}"); done < <(namespaces "${namespace_prefix}")
    local -r n_namespaces="${#namespaces[@]}"

    if [ "${n_namespaces}" = 0 ]; then
      exit 0
    fi

    if [ -z "${current_word}" ]; then
      if [ -d "${SPHYNX_COMMAND_DIR}/${namespace_prefix}" ]; then
        commands "${SPHYNX_COMMAND_DIR}/${namespace_prefix}"
        exit 0
      elif [ "${n_namespaces}" = 1 ] && [ -d "${SPHYNX_COMMAND_DIR}/${namespaces[*]}" ]; then
        commands "${SPHYNX_COMMAND_DIR}/${namespaces[*]}"
        exit 0
      fi
    else
      if [ "${n_namespaces}" -gt 1 ]; then
        for ns in "${namespaces[@]}"; do
          basename "${ns}"
        done

        exit 0
      fi

      basename "${namespaces[*]}"
      exit 0
    fi
  fi

  if [ "${n_args}" -eq 4 ] && [ -n "${current_word}" ]; then
    if [ -d "${SPHYNX_COMMAND_DIR}/${namespace_prefix}" ]; then
      commands "${SPHYNX_COMMAND_DIR}/${namespace_prefix}" | grep -- "${command_prefix}"
      exit 0
    fi

    local namespaces=()
    while IFS='' read -r line; do namespaces+=("${line}"); done < <(namespaces "${namespace_prefix}")
    local -r n_namespaces="${#namespaces[@]}"

    if [ "${n_namespaces}" = 0 ]; then
      exit 0
    fi

    if [ "${n_namespaces}" = 1 ] && [ -d "${SPHYNX_COMMAND_DIR}/${namespaces[*]}" ]; then
      commands "${SPHYNX_COMMAND_DIR}/${namespaces[*]}" | grep -- "${command_prefix}"
      exit 0
    fi
  fi

  exit 1
}

## Running

main "${@}"
