name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Breaking Changes'
    exclusive: true
    semver-increment: 'minor'
    when:
      labels:
        - 'breaking'
  - title: 'Features'
    when:
      labels:
        - 'enhancement'
  - title: 'Bug Fixes'
    when:
      labels:
        - 'bug'
  - title: 'Maintenance'
    when:
      labels:
        - 'chore'
        - 'documentation'
        - 'dependencies'
        - 'github_actions'
  - type: 'pre-exclude'
    when:
      labels:
        - 'no-changelog'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## What's changed

  $CHANGES
