#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_CLI_DIR}/kubernetes/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/postgresql.sh"

##? Connect to/dump/restore and list Kubernetes pods currently connecting to a PostgreSQL database
##?
##? Usage:
##?     postgresql connect --dburi <uri>
##?     postgresql list_connected_pods --dburi <uri>
##?     postgresql (dump | restore) --dburi <uri> --file <filename>
##?
##? Options:
##?     --dburi <uri>  Database URI to connect/dump/restore
##?                    Format: postgresql://<username>:<password>@<host>:<port>/<database-name>
##?     -f --file <filename>  Input/output file name
##?
##? Examples:
##?     postgresql connect --dburi 'postgresql://postgres:postgres@localhost:5432/postgres'
##?     postgresql list_connected_pods --dburi 'postgresql://postgres:postgres@localhost:5432/postgres'
##?     postgresql dump --dburi 'postgresql://qa:qa@localhost:5432/qa' --file qa.tar
##?     postgresql restore --file test.tar --dburi 'postgresql://test:test@localhost:5432/test'

sx::parse_arguments "${@}"

if ${connect:-false}; then
  sx::postgresql::connect "${dburi:-}"
elif ${list_connected_pods:-false}; then
  sx::postgresql::list_connected_pods "${dburi:-}"
elif ${dump:-false}; then
  sx::postgresql::dump "${dburi:-}" "${file:-}"
elif ${restore:-false}; then
  sx::postgresql::restore "${dburi:-}" "${file:-}"
else
  sx::error::illegal_arguments "${*}"
fi
