#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/certificate.sh"

##? Retrieve certificate information from hosts
##?
##? Usage:
##?     certificate <host> [--print | --print-sans]
##?
##? Options:
##?     -p --print  Print the certificate
##?     -s --print-sans  Print the Subject Alternative Name(s)
##?
##? Examples:
##?     certificate google.com --print-sans
##?     certificate youtube.com --print

sx::parse_arguments "${@}"

if ${print:-false}; then
  sx::security::certificate::print "${host:-}"
elif ${print_sans:-false}; then
  sx::security::certificate::print_sans "${host:-}"
else
  sx::error::illegal_arguments "${*}"
fi
