#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/certificate.sh"

##? Fetch certificate information from hosts
##?
##? Usage:
##?     certificate <host> [--sans | --info]
##?
##? Options:
##?     -s --sans  Print the Subject Alternative Name(s)
##?     -i --info  Print full certificate details (subject, issuer, validity, SANs, fingerprint, ...)
##?
##? Examples:
##?     certificate google.com
##?     certificate google.com --sans
##?     certificate youtube.com --info

sx::parse_arguments "${@}"

if ${sans:-false}; then
  sx::security::certificate::sans "${host:-}"
elif ${info:-false}; then
  sx::security::certificate::info "${host:-}"
else
  sx::security::certificate::print "${host:-}"
fi
