#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/branch.sh"

##? Manage GIT branches
##?
##? Usage:
##?     branch (--clear | [<query>] --switch)
##?
##? Options:
##?     -c --clear  Delete all local branches, except the current and the default branches
##?     -s --switch  Switch to another branch interactively
##?
##? Examples:
##?     branch --switch master
##?     branch --switch
##?     branch --clear

sx::parse_arguments "${@}"

if ${clear:-false}; then
  sx::git::branch::delete_all_local
elif ${switch:-false}; then
  sx::git::branch::switch "${query:-}"
else
  sx::error::illegal_arguments "${*}"
fi
