#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/check.sh"

##? Check whether the current branch is up to date with the default branch
##?
##? Usage:
##?     check
##?
##? Examples:
##?     check

sx::parse_arguments "${@}"

sx::git::check
