#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/clone.sh"

##? Clone projects
##?
##? Usage:
##?     clone <username> <project-name> (--https | --ssh)
##?
##? Examples:
##?     clone 'Google' 'knative-gcp' --https
##?     clone 'kubernetes' 'kubernetes' --ssh

sx::parse_arguments "${@}"

if ${https:-false}; then
  sx::git::clone::https "${username:-}" "${project_name:-}"
elif ${ssh:-false}; then
  sx::git::clone::ssh "${username:-}" "${project_name:-}"
else
  sx::error::illegal_arguments "${*}"
fi
