#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/pull_request.sh"

##? Preview the Pull Request changes on the available browser
##?
##? Usage:
##?     pull_request preview
##?
##? Examples:
##?     pull_request preview

sx::parse_arguments "${@}"

sx::git::pull_request::preview
