#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/summary.sh"

##? Print extra information about repositories
##?
##? Usage:
##?     summary --period <time>
##?
##? Options:
##?     -p --period <d | w | m | y>  The period that you wish to see a summary
##?
##? Examples:
##?     summary --period d  # Last 24 hours
##?     summary --period w  # Last 7 days
##?     summary --period m  # Last 30 days
##?     summary --period y  # Last 12 months

sx::parse_arguments "${@}"

sx::git::summary::repository "${period:-}"
