- name: Alacritty - Creating configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    mode: "0755"
    state: directory

- name: Alacritty - Checking installation
  stat:
    path: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
  register: alacritty

- name: Alacritty - Installing personal settings
  file:
    src: "{{ sphynx_settings_directory }}/macos/alacritty/alacritty.yaml"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
    state: link
    force: yes
  when:
    - not alacritty.stat.exists or (alacritty.stat.islnk is defined and not alacritty.stat.islnk)
