- name: Detecting - Google Chrome is available
  stat:
    path: "/usr/bin/google-chrome"
  register: chrome

- name: Downloading Google Chrome
  get_url:
    url: "{{ google_chrome_url }}"
    dest: "{{ google_chrome_dest }}"
  when:
    - not chrome.stat.exists

- name: Installing Google Chrome
  become: true
  shell: |
    dpkg -i {{ google_chrome_dest }}
    apt-get install -f
  when:
    - not chrome.stat.exists
