#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/open.sh"

##? Open resources using the available browser
##?
##? Usage:
##?     open [<any>...]
##?
##? Examples:
##?     open .
##?     open "https://google.com"

sx::parse_arguments "${@}"

sx::browser::open "${any[@]:-.}"
