- name: Installing Karabiner Elements
  community.general.homebrew_cask:
    name: karabiner-elements
    state: present

- name: Creating directories
  file:
    path: "{{ ansible_env.HOME }}/.config/karabiner"
    state: directory

- name: Installing personal settings
  file:
    src: "{{ sphynx_settings_directory }}/macos/karabiner-elements/karabiner.json"
    dest: "{{ ansible_env.HOME }}/.config/karabiner/karabiner.json"
    state: link
    force: yes
  notify:
    - Restart Karabiner Elements
