#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/activity.sh"

##? Print current activity name
##?
##? Usage:
##?     activity
##?
##? Examples:
##?     activity

sx::parse_arguments "${@}"

sx::android::activity::current
