# -*- mode: ruby -*-
# vi: set ft=ruby :

# Reference:
# - [Available Boxes]: https://vagrantcloud.com/search
# - [CLI Docs]: https://www.vagrantup.com/docs/cli
# - [Forwarded Ports]: https://www.vagrantup.com/docs/networking/forwarded_ports
# - [Private Networks]: https://www.vagrantup.com/docs/networking/private_network
# - [Public Networks]: https://www.vagrantup.com/docs/networking/public_network

Vagrant.configure("2") do |config|

  # https://portal.cloud.hashicorp.com/vagrant/discover/bento/ubuntu-24.04
  config.vm.box = "bento/ubuntu-24.04"

  # https://parallels.github.io/vagrant-parallels/docs/
  config.vm.provider "parallels" do |vb|
    vb.name = "Ubuntu_24_04"

    vb.memory = "2048" # 2GiB
    vb.cpus = "2" # 2vCPUs
  end

  # https://www.vagrantup.com/docs/synced-folders
  # By default, Vagrant will share your project directory (the directory with the Vagrantfile) to /vagrant.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
  SHELL
end
