#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/gateway.sh"

##? Print gateway ip
##?
##? Usage:
##?     gateway
##?
##? Examples:
##?     gateway

sx::parse_arguments "${@}"

sx::ip::gateway
