#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/private.sh"

##? Print private ip(s)
##?
##? Usage:
##?     private
##?
##? Examples:
##?     private

sx::parse_arguments "${@}"

sx::ip::private
