- name: Detecting - Firefox Developer Edition is available
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/firefox-developer-edition"
  register: firefox

- name: Downloading Firefox Developer Edition
  get_url:
    url: "{{ firefox_url }}"
    dest: "{{ firefox_dest }}"
  when:
    - not firefox.stat.exists

- name: Creating directory for Firefox Developer Edition
  file: "path=/opt/firefox-developer-edition mode=0755 state=directory"
  become: true
  when:
    - not firefox.stat.exists

- name: Unarchiving Firefox Developer Edition
  become: true
  unarchive:
    src: "{{ firefox_dest }}"
    dest: /opt/firefox-developer-edition
    remote_src: yes
  when:
    - not firefox.stat.exists

- name: Copying Firefox Developer Edition icon
  become: true
  copy:
    src: icon.png
    dest: /opt/firefox-developer-edition/firefox/icon.png
  when:
    - not firefox.stat.exists

- name: Creating bin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0755
    state: directory
  when:
    - not firefox.stat.exists

- name: Creating link for Firefox Developer Edition
  file:
    src: /opt/firefox-developer-edition/firefox/firefox
    dest: "{{ ansible_env.HOME }}/.local/bin/firefox-developer-edition"
    state: link
  when:
    - not firefox.stat.exists

- name: Creating Firefox Developer Edition launcher
  template:
    src: firefox-developer-edition.desktop.j2
    dest: "{{ ansible_env.HOME }}/.local/share/applications/firefox-developer-edition.desktop"
  when:
    - not firefox.stat.exists
