version: "3"

vars:
  REPOSITORY: hpedrorodrigues/tools

tasks:
  builder:
    cmds:
      - docker buildx create --name multiarch --driver docker-container --use
  build:
    vars:
      IMAGES: hadolint
      PLATFORM: linux/amd64,linux/arm64
    cmds:
      - for: { var: IMAGES }
        cmd: docker buildx build '{{ .ITEM }}' --platform '{{ .PLATFORM }}' --tag '{{ .REPOSITORY }}:{{ .ITEM }}' {{.CLI_ARGS}}
