- name: Installing ZSH
  community.general.homebrew:
    name: zsh
    state: present

- name: Adding Homebrew ZSH to /etc/shells
  lineinfile:
    path: /etc/shells
    search_string: /usr/local/bin/zsh
    line: /usr/local/bin/zsh
  become: true
  when:
    - lookup('env','SHELL') != '/usr/local/bin/zsh'

- name: Setting default shell
  shell: "chsh -s /usr/local/bin/zsh {{ ansible_env.USER }}"
  become: true
  when:
    - lookup('env','SHELL') != '/usr/local/bin/zsh'

- name: Configuring Dotfiles
  command: "{{ sphynx_cli }} workstation setup --dotfiles"

- name: Include additional tasks
  include_tasks:
    file: "{{ item }}"
  loop:
    - vundle.yml
    - fonts.yml
    - terminal.yml
    - starship.yml
    - rectangle.yml
    - editor.yml
