- name: Detecting - Inventory is available
  stat:
    path: "{{ inventory_path }}"
  register: inventory

- name: Getting current inventory state
  shell: "test -f {{ inventory_path }} && cat {{ inventory_path }} || echo"
  register: inventory_state
  changed_when: false
  when:
    - inventory.stat.exists

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
- name: Closing System Preferences
  shell: |
    osascript -e 'tell application "System Preferences" to quit'
  register: system_preferences
  changed_when: system_preferences.rc != 0

- name: Applying defaults
  script: "{{ item }}"
  with_items:
    - "{{ lookup('fileglob', '*.defaults').split(',') }}"
  register: defaults
  notify:
    - Restart Finder
    - Restart Dock
    - Restart System UI Server
    - Restart Mail
  when:
    - not inventory.stat.exists or lookup('file', item) | checksum not in inventory_state.stdout

- name: Creating inventory file
  file:
    path: "{{ inventory_path }}"
    state: touch
  when:
    - not inventory.stat.exists
    - defaults is succeeded

- name: Updating inventory with current state
  lineinfile:
    line: "{{ lookup('file', item) | checksum }}"
    dest: "{{ inventory_path }}"
    state: present
  with_items:
    - "{{ lookup('fileglob', '*.defaults').split(',') }}"
  when:
    - not inventory.stat.exists or lookup('file', item) | checksum not in inventory_state.stdout
