#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNX_DIR}/.file/common/scripts/alien.sh"

##? Run formatters
##?
##? Usage:
##?     fmt
##?
##? Examples:
##?     fmt

if [ "${#}" -ne '0' ]; then
  sx::parse_arguments "${@}"
fi

sx::self::fmt
