#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNX_DIR}/.file/common/alien"

##? Run linters
##?
##? Usage:
##?     lint
##?
##? Examples:
##?     lint

if [ "${#}" -ne '0' ]; then
  sx::parse_arguments "${@}"
fi

sx::self::lint
