#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"

##? Display a preview for each command available
##?
##? Usage:
##?     prompt
##?
##? Examples:
##?     prompt

if [ "${#}" -ne '0' ]; then
  sx::parse_arguments "${@}"
fi

sx::self::prompt
