#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"

##? Print current version
##?
##? Usage:
##?     version
##?
##? Examples:
##?     version

if [ "${#}" -ne '0' ]; then
  sx::parse_arguments "${@}"
fi

sx::self::version
