#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"

##? Print current version
##?
##? Usage:
##?     version

sx::parse_arguments "${@}"

sx::self::version
