command_timeout = 750

format = """
$username\
$hostname\
$directory\
$time\
$git_branch\
$git_commit\
$git_status\
$kubernetes\
$aws\
$gcloud\
$cmd_duration\
$line_break\
$jobs\
$character
"""

[username]
show_always = true
format = "╭─[$user]($style)"
style_user = "bold white"

[hostname]
ssh_only = false
format = "@[$hostname]($style) "
style = "white"

[directory]
truncation_length = 7
truncate_to_repo = false
truncation_symbol = "…/"
style = "bold white"

[time]
disabled = false
time_format = "%I:%M %p | %v"
format = "[$time]($style) "
style = "white"

[git_branch]
format = "[$symbol$branch]($style) "
style = "fg:#50fa7b"

[git_commit]
commit_hash_length = 5
only_detached = false
style = "fg:#50fa7b"

[git_status]
style = "fg:#50fa7b"

[kubernetes]
disabled = false
symbol = "☀ "
format = "[$symbol$context(\\($namespace\\))]($style) "
style = "fg:#8be9fd"
contexts = [
  { context_pattern = "gke_.*_(?P<cluster>[\\w-]+)", context_alias = "$cluster" },
]

[aws]
symbol = "❄ "
format = "[$symbol$profile(\\($region\\))]($style) "
style = "fg:#ffb86c"

[gcloud]
symbol = "☸ "
format = "[$symbol$project(\\($region\\))]($style) "
style = "fg:#bd93f9"

[cmd_duration]
min_time = 5_000
format = "[$duration]($style) "
style = "bright-red"

[character]
success_symbol = "[♪](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[ⓥ](bold yellow)"
