#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/dashboard.sh"

##? Retrieve the dashboard
##?
##? Usage:
##?     dashboard [<target>] [<query>] [--namespace <name> | --all-namespaces] [--port <number>]
##?
##? Arguments:
##?     <target>  Dashboard target (envoy-gateway or envoy-proxy)
##?     <query>   Filter query for pod selection (envoy-proxy target only)
##?
##? Options:
##?     -n --namespace <name>   Namespace scope for requests
##?     -a --all-namespaces     Search all namespaces
##?     -p --port <number>      Local port to use for the dashboard
##?
##? Examples:
##?     dashboard
##?     dashboard envoy-gateway
##?     dashboard envoy-gateway --namespace envoy-gateway-system
##?     dashboard envoy-gateway --port 8080
##?     dashboard envoy-proxy
##?     dashboard envoy-proxy --namespace my-namespace
##?     dashboard envoy-proxy --all-namespaces

sx::parse_arguments "${@}"

sx::eg::dashboard \
  "${target:-}" \
  "${query:-}" \
  "${namespace:-}" \
  "${all_namespaces:-false}" \
  "${port:-}"
