#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/reload-completion.sh"

##? Reload zsh completions
##?
##? Usage:
##?     reload-completion zsh
##?
##? Examples:
##?     reload-completion zsh

sx::parse_arguments "${@}"

sx::shell::reload_completion::zsh
