#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/ui.sh"

##? Manage MacOS ui
##?
##? Usage:
##?     ui (--restart | --hidden-files <state> | --spotlight-indexing <state>)
##?
##? Options:
##?     --restart  The System UI Server will be restarted
##?     --hidden-files <state>  Changes finder to display all files (on|off)
##?     --spotlight-indexing <state>  Changes indexing state of Spotlight (on|off). Root access required.
##?
##? Examples:
##?     ui --restart
##?     ui --hidden-files on
##?     ui --spotlight-indexing off

sx::parse_arguments "${@}"

if ${restart:-}; then
  sx::macos::restart_ui
elif [ -n "${hidden_files:-}" ]; then
  if [ "${hidden_files}" = 'on' ] || [ "${hidden_files}" = 'off' ]; then
    sx::macos::show_hidden_files "${hidden_files}"
  else
    sx::error::illegal_arguments "${*}"
  fi
elif [ -n "${spotlight_indexing:-}" ]; then
  if [ "${spotlight_indexing}" = 'on' ] || [ "${spotlight_indexing}" = 'off' ]; then
    sx::macos::change_spotlight_indexing_state "${spotlight_indexing}"
  else
    sx::error::illegal_arguments "${*}"
  fi
else
  sx::error::illegal_arguments "${*}"
fi
