#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/setup.sh"

##? Configure personal workstation
##?
##? Usage:
##?     setup
##?
##? Examples:
##?     setup

if [ "${#}" -ne '0' ]; then
  sx::parse_arguments "${@}"
fi

sx::workstation::setup
