#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_DIR}/modules/dotfiles/common/scripts/alien.sh"

##? Run linters
##?
##? Usage:
##?     lint
##?
##? Examples:
##?     lint

if [ "${#}" -ne '0' ]; then
  sx::parse_arguments "${@}"
fi

sx::self::lint
