#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"

##? Run tests
##?
##? Usage:
##?     test
##?
##? Examples:
##?     test

if [ "${#}" -ne '0' ]; then
  sx::parse_arguments "${@}"
fi

sx::self::test
