#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/certificate.sh"

##? Retrieve certificate information from hosts
##?
##? Usage:
##?     certificate --host <address> [--get | --sans]
##?
##? Options:
##?     -h --host <address>  The domain address to get information from
##?     -g --get  Print the certificate
##?     -s --sans  Print the Subject Alternative Name(s)
##?
##? Examples:
##?     certificate --host google.com --sans
##?     certificate -h youtube.com -g

sx::parse_arguments "${@}"

if ${get:-false}; then
  sx::security::certificate::get "${host:-}"
elif ${sans:-false}; then
  sx::security::certificate::sans "${host:-}"
else
  sx::error::illegal_arguments "${*}"
fi
