#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/hash.sh"

##? Run hashing algorithms against files
##?
##? Usage:
##?     hash (md5 | sha1 | sha256) [<filenames>...]
##?
##? Examples:
##?     hash md5 'example.tar.gz'
##?     hash sha1 'example.tar.gz'
##?     hash sha256 'example.tar.gz'

sx::parse_arguments "${@}"

# shellcheck disable=SC2068  # Double quote array expansions
if ${md5:-false}; then
  sx::security::hash::md5 ${filenames[@]:-}
elif ${sha1:-false}; then
  sx::security::hash::sha1 ${filenames[@]:-}
elif ${sha256:-false}; then
  sx::security::hash::sha256 ${filenames[@]:-}
else
  sx::error::illegal_arguments "${*}"
fi
