- name: Creating Go configuration directory
  file:
    path: "{{ workspace }}"
    state: directory

- name: Installing Go packages
  shell: "GOPATH={{ workspace }} {{ go_bin }} install {{ item.repository }}"
  loop: "{{ packages }}"
