- name: Loading existing items
  shell: "dockutil --list | awk -F '\t' '{ print $1 }'"
  register: current_items
  changed_when: false

- name: Removing all existing items
  command: dockutil --no-restart --remove all
  when:
    - applications != current_items.stdout.split('\n')

- name: Adding new items
  shell: "dockutil --no-restart --add '{{ item }}' '{{ ansible_env.HOME }}/Library/Preferences/com.apple.dock.plist'"
  loop: "{{ applications }}"
  notify:
    - Restart Dock
  when:
    - item not in current_items.stdout.split('\n') or applications != current_items.stdout.split('\n')
