#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/ecr.sh"

##? Amazon Elastic Container Registry utilities
##?
##? Usage:
##?     ecr delete-untagged (--all | --repository <repository-name>)
##?
##? Options:
##?     -a --all  Delete all untagged images from all repositories
##?     -r --repository <repository-name>  Delete all untagged images from the repository
##?
##? Examples:
##?     ecr delete-untagged --all
##?     ecr delete-untagged --repository my-repo

sx::parse_arguments "${@}"

if [ -n "${repository:-}" ]; then
  sx::aws::ecr::delete_untagged_images_from_repository "${repository}"
elif ${all:-false}; then
  sx::aws::ecr::delete_untagged_images_from_all_repositories
fi
