#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/delete.sh"

##? Remove one or more objects
##?
##? Usage:
##?     delete
##?
##? Examples:
##?     delete

sx::parse_arguments "${@}"

sx::nerdctl::delete
