#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/inspect.sh"

##? Return low-level information on objects
##?
##? Usage:
##?     inspect
##?
##? Examples:
##?     inspect

sx::parse_arguments "${@}"

sx::nerdctl::inspect
