#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/logs.sh"

##? Fetch logs of containers
##?
##? Usage:
##?     logs [--container <id>]
##?
##? Options:
##?     -c --container <id>  The container id to tail logs from
##?
##? Examples:
##?     logs

sx::parse_arguments "${@}"

sx::nerdctl::logs "${container:-}"
