#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/pid.sh"

##? Print the process id (PID) of a container
##?
##? Usage:
##?     pid
##?
##? Examples:
##?     pid

sx::parse_arguments "${@}"

sx::nerdctl::pid
