# https://alacritty.org/config-alacritty.html
[general]
live_config_reload = true

[terminal]

[terminal.shell]
program = "/usr/local/bin/zsh"
args = [
  "--login",
  "--interactive",
  "-c",
  "sx terminal tmux force-attach 'sphynx'",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
dimensions = { columns = 120, lines = 40 }
padding = { x = 5 }

[scrolling]
history = 100000
multiplier = 5

# As of the writing of this comment, Alacritty doesn't support ligatures.
# Configuring Fira Code here hoping it eventually supports.
[font]
size = 12.0
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Retina" }
bold_italic = { family = "Fira Code", style = "SemiBold" }

[colors]
primary = { background = "#0b0b0d", foreground = "#e5e5e5" }
normal = { black = "#191919", blue = "#045b96", cyan = "#28c3d4", green = "#329932", magenta = "#e500e5", red = "#da1e37", white = "#e5e5e5", yellow = "#ffff00" }
bright = { black = "#6c757d", blue = "#3282b8", cyan = "#3fc5f0", green = "#66b266", magenta = "#ff00ff", red = "#f94144", white = "#ffffff", yellow = "#ffff66" }
dim = { black = "#000000", blue = "#0f4c75", cyan = "#22b9ca", green = "#008000", magenta = "#cc00cc", red = "#b20000", white = "#cccccc", yellow = "#e5e500" }

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
style = { shape = "Underline" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{ key = 40, mods = "Command", action = "ClearHistory" }]
