enable_experimental_conpty_backend = false
live_config_reload = false

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = []

[colors.bright]
black = "#6c757d"
blue = "#3282b8"
cyan = "#3fc5f0"
green = "#66b266"
magenta = "#ff00ff"
red = "#f94144"
white = "#ffffff"
yellow = "#ffff66"

[colors.dim]
black = "#000000"
blue = "#0f4c75"
cyan = "#22b9ca"
green = "#008000"
magenta = "#cc00cc"
red = "#b20000"
white = "#cccccc"
yellow = "#e5e500"

[colors.normal]
black = "#191919"
blue = "#045b96"
cyan = "#28c3d4"
green = "#329932"
magenta = "#e500e5"
red = "#da1e37"
white = "#e5e5e5"
yellow = "#ffff00"

[colors.primary]
background = "#0b0b0d"
foreground = "#e5e5e5"

[cursor]
style = "Underline"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Fira Code"
style = "Light"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ClearHistory"
key = 40
mods = "Command"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/usr/local/bin/zsh"
args = ["--login", "--interactive", "-c", "sx terminal tmux force-attach 'sphynx'"]

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.9
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 10
y = 10
