#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/whatsapp.sh"

##? Open whatsapp chats on browser
##?
##? Usage:
##?     whatsapp <phone> [--text <message>]
##?
##? Options:
##?     -t --text <message>  Open the chat with the provided text
##?
##? Examples:
##?     whatsapp "+5511999991111"
##?     whatsapp "+19991119999" --text "Hey, how's it going?"

sx::parse_arguments "${@}"

sx::share::whatsapp "${phone:-}" "${text:-}"
