#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_CLI_DIR}/kubernetes/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/arenas.sh"

##? Report the memory glibc holds for a JVM process running in a Kubernetes pod
##?
##? Usage:
##?     arenas [<query>] [--image <image>] [--selector <selector>] [--namespace <name> | --all-namespaces] [--context <name>]
##?     arenas --namespace <name> --pod <name> --container <name> [--image <image>] [--context <name>]
##?
##? Options:
##?     -l --selector <selector>  Selector (label query) to filter on
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -p --pod <name>  The pod name
##?     -c --container <name>  The container name
##?     --image <image>  Image of the ephemeral container running "gdb", e.g. ghcr.io/hpedrorodrigues/gdb. Required, and every thread of the JVM stops while it runs
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     arenas --image ghcr.io/hpedrorodrigues/gdb
##?     arenas keycloak --image ghcr.io/hpedrorodrigues/gdb
##?     arenas --selector app=kafka --image ghcr.io/hpedrorodrigues/gdb
##?     arenas --namespace kafka --pod kafka-0 --container kafka --image ghcr.io/hpedrorodrigues/gdb
##?     arenas kafka --image ghcr.io/hpedrorodrigues/gdb --context staging

sx::parse_arguments "${@}"

sx::jvm::arenas \
  "${query:-}" \
  "${selector:-}" \
  "${namespace:-}" \
  "${pod:-}" \
  "${container:-}" \
  "${all_namespaces:-false}" \
  "${context:-}" \
  "${image:-}"
