#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_CLI_DIR}/kubernetes/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/nativememory.sh"

##? Report the native memory usage of a JVM process running in a Kubernetes pod
##?
##? Usage:
##?     nativememory [<query>] [--level <level>] [--selector <selector>] [--namespace <name> | --all-namespaces] [--image <image>] [--context <name>]
##?     nativememory --namespace <name> --pod <name> --container <name> [--level <level>] [--image <image>] [--context <name>]
##?
##? Options:
##?     --level <level>  Report level: summary or detail (requires -XX:NativeMemoryTracking) [default: summary]
##?     -l --selector <selector>  Selector (label query) to filter on
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -p --pod <name>  The pod name
##?     -c --container <name>  The container name
##?     --image <image>  Run the JDK tooling from an ephemeral container with this image, instead of from the target container (for JRE-only/distroless images). Prefer a version equal to or newer than the target JVM, e.g. eclipse-temurin:21-jdk
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     nativememory
##?     nativememory kafka
##?     nativememory kafka --level detail
##?     nativememory --selector app=kafka
##?     nativememory --namespace kafka --pod kafka-0 --container kafka --level summary
##?     nativememory keycloak --level detail --image eclipse-temurin:21-jdk
##?     nativememory kafka --context staging

sx::parse_arguments "${@}"

sx::jvm::nativememory \
  "${query:-}" \
  "${selector:-}" \
  "${namespace:-}" \
  "${pod:-}" \
  "${container:-}" \
  "${level:-summary}" \
  "${all_namespaces:-false}" \
  "${context:-}" \
  "${image:-}"
