#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/email.sh"

##? Get user email
##?
##? Usage:
##?     email <username>
##?
##? Examples:
##?     email octocat

sx::parse_arguments "${@}"

sx::github::email "${username:-}"
