#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/email.sh"

##? Get user email
##?
##? Usage:
##?     email <username>
##?
##? Examples:
##?     email octocat

sx::parse_arguments "${@}"

sx::github::email "${username:-}"
