#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/ls.sh"

##? List catalog specifications
##?
##? Usage:
##?     ls [--name <name>] [--prefix <prefix>] [--captures | --collections | --materializations | --tests] [--flows]
##?
##? Options:
##?     --name <name>  Only include the specification with this exact name
##?     --prefix <prefix>  Only include specifications whose name starts with this prefix
##?     -c --captures  Only include captures
##?     --collections  Only include collections
##?     --materializations  Only include materializations
##?     --tests  Only include tests
##?     -f --flows  Include the data-flows of each specification
##?
##? Examples:
##?     ls
##?     ls --captures
##?     ls --prefix acme/
##?     ls --name acme/anvils/orders
##?     ls --collections --flows
##?     ls --materializations

sx::parse_arguments "${@}"

sx::flow::ls \
  "${name:-}" \
  "${prefix:-}" \
  "${captures:-false}" \
  "${collections:-false}" \
  "${materializations:-false}" \
  "${tests:-false}" \
  "${flows:-false}"
