#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/ecr.sh"

##? Amazon Elastic Container Registry utilities
##?
##? Usage:
##?     ecr (--clear-untagged | --delete-untagged <repository-name>)
##?
##? Options:
##?     -c --clear-untagged  Delete all untagged images from all repositories
##?     -d --delete-untagged <repository-name>  Delete all untagged images from the repository
##?
##? Examples:
##?     ecr --clear-untagged
##?     ecr --delete-untagged my-repo

sx::parse_arguments "${@}"

if ${clear_untagged:-false}; then
  sx::aws::ecr::clear_untagged
elif [ -n "${delete_untagged:-}" ]; then
  sx::aws::ecr::delete_untagged_from_repository "${delete_untagged}"
fi
