- name: Creating Alacritty configuration directory
  file: "path={{ ansible_env.HOME }}/.config/alacritty mode=0755 state=directory"

- name: Detecting - Alacrity is available
  stat:
    path: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
  register: alacritty

- name: Installing Alacritty settings
  file:
    src: "{{ applications_settings_dir }}/osx/alacritty/alacritty.yaml"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
    state: link
    force: yes
  when:
    - not alacritty.stat.exists or (alacritty.stat.islnk is defined and not alacritty.stat.islnk)
