- name: Detecting - Zsh is available
  stat:
    path: "/usr/local/bin/zsh"
  register: zsh

- name: Installing Zsh package
  homebrew:
    name: "zsh"
    state: present
    upgrade_all: yes
  register: new_zsh
  when:
    - not zsh.stat.exists

- name: Making Zsh the default shell
  shell: "chsh -s /usr/local/bin/zsh"
  when:
    - zsh.stat.exists or new_zsh.rc == 0
    - lookup('env','SHELL') != '/usr/local/bin/zsh'

- name: Installing Dotfiles
  command: "{{ sphynx_cli }} dotfiles configure"
  when:
    - zsh.stat.exists or new_zsh.rc == 0

- name: Configuring Vundle
  include: vundle.yml

- name: Configuring Fonts
  include: fonts.yml

- name: Configuring Alacritty
  include: alacritty.yml

- name: Configuring Starship
  include: starship.yml
