#!/usr/bin/env bash

## Aliases

# System

alias afk='gnome-screensaver-command --lock'
alias ls='ls --color=tty'

# Packaging Tool

alias aptu='sudo apt-get update -y'
alias apti='sudo apt-get install -y'
alias aptr='sudo apt-get remove'
alias apts='sudo apt-cache search'

# Updates

# shellcheck disable=SC1004  # This backslash+linefeed is literal
alias upos='sudo apt update -y \
              && sudo apt-get update -y \
              && sudo apt-get upgrade -y \
              && sudo apt autoremove -y \
              && sudo apt autoclean -y \
              && sudo apt clean -y'

# shellcheck disable=SC1004  # This backslash+linefeed is literal
alias upsnap='sudo snap refresh'

# shellcheck disable=SC1004  # This backslash+linefeed is literal
alias upbrew='brew update \
                && brew upgrade \
                && brew cleanup -s --prune 30'

# shellcheck disable=SC1004  # This backslash+linefeed is literal
alias upnpm='npm install --global npm \
              && npm --global cache clean --force \
              && npm --global update'

alias upall='upos && upsnap && upbrew && upnpm'
