#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_CLI_DIR}/system/core/clipboard.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/inspect.sh"

##? Starts a server in order to inspect HTTP requests made to it
##?
##? Usage:
##?     inspect [--port <port>] [--status-code <code>] [--response-body <body>] [--compact]
##?
##? Options:
##?     -p --port <port>  Port used to listen to
##?     -s --status-code <code>  Status code to return for all requests
##?     -r --response-body <body>  Response body to return for all requests
##?     -c --compact  Hide raw values (e.g., raw URL, raw request body)
##?
##? Examples:
##?     inspect
##?     inspect --port 4000

sx::parse_arguments "${@}"

sx::http::inspect "${port:-}" "${status_code:-}" "${response_body:-}" "${compact:-}"
