- name: Cloning repositories
  git: "repo={{ item.repo }} dest={{ item.dest }} update=no"
  loop: "{{ repositories }}"

- name: Running hooks
  shell: "{{ item.hooks }}"
  loop: "{{ repositories }}"
  when:
    - item.hooks is defined
