#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/reconcile.sh"

##? Reconcile a Flux resource
##?
##? Usage:
##?     reconcile [<query>] [--namespace <name> | --all-namespaces]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -a --all-namespaces  All namespaces
##?
##? Examples:
##?     reconcile
##?     reconcile my-app
##?     reconcile --namespace flux-system
##?     reconcile --all-namespaces

sx::parse_arguments "${@}"

sx::flux::reconcile \
  "${query:-}" \
  "${namespace:-}" \
  "${all_namespaces:-false}"
