#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/reconcile.sh"

##? Reconcile a Flux resource
##?
##? Usage:
##?     reconcile [[<query>] [--namespace <name> | --all-namespaces] | <kind> <name> [--namespace <name>]]
##?
##? Arguments:
##?     <kind>  The Flux resource kind (e.g., kustomization, helmrelease, gitrepository)
##?     <name>  The Flux resource name
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?
##? Examples:
##?     reconcile
##?     reconcile my-app
##?     reconcile --namespace flux-system
##?     reconcile --all-namespaces
##?     reconcile kustomization my-app
##?     reconcile kustomization my-app --namespace flux-system

sx::parse_arguments "${@}"

sx::flux::reconcile \
  "${query:-}" \
  "${namespace:-}" \
  "${all_namespaces:-false}" \
  "${kind:-}" \
  "${name:-}"
