#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/reconcile.sh"

##? Reconcile a Flux resource
##?
##? Usage:
##?     reconcile --list [[<query>] [--namespace <name> | --all-namespaces]]
##?     reconcile [[<query>] [--namespace <name> | --all-namespaces] | <kind> <name> [--namespace <name>]]
##?
##? Arguments:
##?     <kind>  The Flux resource kind (e.g., kustomization, helmrelease, gitrepository)
##?     <name>  The Flux resource name
##?
##? Options:
##?     -l --list  List all resources that can be reconciled
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?
##? Examples:
##?     reconcile --list
##?     reconcile --list --all-namespaces
##?     reconcile --list my-app
##?     reconcile
##?     reconcile my-app
##?     reconcile --namespace flux-system
##?     reconcile --all-namespaces
##?     reconcile kustomization my-app
##?     reconcile kustomization my-app --namespace flux-system

sx::parse_arguments "${@}"

if ${list:-false}; then
  sx::flux::reconcile::list \
    "${query:-}" \
    "${namespace:-}" \
    "${all_namespaces:-false}"
else
  sx::flux::reconcile \
    "${query:-}" \
    "${namespace:-}" \
    "${all_namespaces:-false}" \
    "${kind:-}" \
    "${name:-}"
fi
