#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/resume.sh"

##? Resume a Flux resource
##?
##? Usage:
##?     resume [<query>] [--namespace <name> | --all-namespaces]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -a --all-namespaces  All namespaces
##?
##? Examples:
##?     resume
##?     resume my-app
##?     resume --namespace flux-system
##?     resume --all-namespaces

sx::parse_arguments "${@}"

sx::flux::resume \
  "${query:-}" \
  "${namespace:-}" \
  "${all_namespaces:-false}"
