#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/activity.sh"

##? Print current activity name
##?
##? Usage:
##?     activity [--device <serial>]
##?
##? Options:
##?     --device <serial>  The serial number of the device to target
##?
##? Examples:
##?     activity
##?     activity --device emulator-5554

sx::parse_arguments "${@}"

sx::android::activity::current "${device:-}"
