#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/analyze.sh"

##? Analyze APK files and installed applications
##?
##? Usage:
##?     analyze --apk <file> [--device <serial>]
##?     analyze --app [<query>] [--device <serial>]
##?
##? Options:
##?     --apk <file>  Analyze the given APK file
##?     --app  Analyze the installed app selected by the query
##?     --device <serial>  The serial number of the device to target
##?
##? Arguments:
##?     <query>  Filter matching the package name of an installed app
##?
##? Examples:
##?     analyze --apk "android.apk"
##?     analyze --apk "${HOME}/Downloads/twitter.apk"
##?     analyze --app "telegram"
##?     analyze --app "com.google.android.keep"

sx::parse_arguments "${@}"

if [ -n "${apk:-}" ]; then
  sx::android::analyze::apk "${apk}"
elif ${app:-false}; then
  sx::android::analyze::app "${query:-}" "${device:-}"
else
  sx::error::illegal_arguments "${*}"
fi
