#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/instrumentation.sh"

##? Manage instrumentation apps installed on a device
##?
##? Usage:
##?     instrumentation [--device <serial>]
##?     instrumentation --uninstall [<query>] [--device <serial>]
##?
##? Options:
##?     -u --uninstall  Uninstall the instrumentation app selected by the query
##?     --device <serial>  The serial number of the device to target
##?
##? Arguments:
##?     <query>  Filter matching the package name of an instrumentation app
##?
##? Examples:
##?     instrumentation
##?     instrumentation -u "webview_shell"
##?     instrumentation --uninstall "org.chromium.webview_shell"

sx::parse_arguments "${@}"

if ${uninstall:-false}; then
  sx::android::instrumentation::uninstall "${query:-}" "${device:-}"
else
  sx::android::instrumentation::list "${device:-}"
fi
