#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/screenshot.sh"

##? Take screenshots from devices
##?
##? Usage:
##?     screenshot [--name <file>] [--device <serial>]
##?
##? Options:
##?     -n --name <file>  Name of file to be saved
##?     --device <serial>  The serial number of the device to target
##?
##? Examples:
##?     screenshot
##?     screenshot --name "Screenshot.png"

sx::parse_arguments "${@}"

sx::android::screenshot::take "${name:-}" "${device:-}"
