scan_timeout = 15

format = """
$hostname\
$directory\
"""

[hostname]
ssh_only = false
style = "fg:#bd93f9"
format = "[$hostname]($style) at "

[directory]
truncation_length = 7
truncate_to_repo = false
style = "fg:#50fa7b"
