- name: Updating all packages
  apt:
    name: "*"
    state: latest
    update_cache: true

- name: Removing useless packages from the cache
  apt:
    autoclean: yes

- name: Removing dependencies that are no longer required
  apt:
    autoremove: yes

- name: Adding repositories
  apt_repository:
    repo: "{{ repositories }}"
    state: present

- name: Installing packages
  apt:
    name: "{{ packages }}"
    state: present
