- name: Updating all packages
  apt:
    name: "*"
    state: latest
    update_cache: true

- name: Removing useless packages from the cache
  apt:
    autoclean: yes

- name: Removing dependencies that are no longer required
  apt:
    autoremove: yes

- name: Enabling built-in repositories
  shell: add-apt-repository -y {{ item }}
  loop: "{{ builtin_repositories }}"

- name: Installing packages
  apt:
    name: "{{ packages }}"
    state: present
