#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/extract.sh"

##? Extract bundled or compressed files
##?
##? Usage:
##?     extract <file_path>
##?
##? Examples:
##?     extract "file.zip"
##?     extract "file.tar.gz"

sx::parse_arguments "${@}"

sx::fs::extract "${file_path:-}"
