#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/api-versions.sh"

##? Print the supported API versions on the server and the available resources
##? kind in each one
##?
##? Usage:
##?     api-versions
##?
##? Examples:
##?     api-versions

sx::parse_arguments "${@}"

sx::k8s::api_versions
