#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/context.sh"

##? Manage contexts
##?
##? Usage:
##?     context [<query> | --list | --exact <name> | -]
##?
##? Options:
##?     -l --list  Print all contexts
##?     -e --exact <name>  Name to be used without checking for it
##?
##? Examples:
##?     context
##?     context prd
##?     context --exact staging
##?     context --list
##?     context -

sx::parse_arguments "${@}"

sx::k8s::context "${query:-}" "${exact:-}" "${list:-false}"
