#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/exec.sh"

##? Execute custom commands in a container
##?
##? Usage:
##?     exec [[<query>] [--namespace <name> | --all-namespaces] | --namespace <name> --pod <name> --container <name>]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -a --all-namespaces  All namespaces
##?     -p --pod <name>  The pod name
##?     -c --container <name>  The container name
##?
##? Examples:
##?     exec
##?     exec echo-server
##?     exec echo-server --all-namespaces
##?     exec --namespace echo-server --pod echo-server --container echo-server
##?     exec --namespace kube-system
##?     exec --all-namespaces

sx::parse_arguments "${@}"

sx::k8s::exec \
  "${query:-}" \
  "${namespace:-}" \
  "${pod:-}" \
  "${container:-}" \
  "${all_namespaces:-false}"
