#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/exec.sh"

##? Execute custom commands in a container
##?
##? Usage:
##?     exec [<query>] [--namespace <name> | --all-namespaces]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -a --all-namespaces  All namespaces
##?
##? Examples:
##?     exec
##?     exec echo-server
##?     exec --namespace kube-system
##?     exec --all-namespaces

sx::parse_arguments "${@}"

sx::k8s::exec "${query:-}" "${namespace:-}" "${all_namespaces:-false}"
