#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/port-forward.sh"

##? Forward one local port to a pod
##?
##? Usage:
##?     port-forward [<query>] [--namespace <name> | --all-namespaces] [--random-port | --port <number>]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -a --all-namespaces  All namespaces
##?     -r --random-port  Bind a random port locally
##?     -p --port <number>  Bind to the given port
##?
##? Examples:
##?     port-forward
##?     port-forward nginx
##?     port-forward --namespace kube-system --random-port
##?     port-forward --all-namespaces
##?     port-forward --port 8080

sx::parse_arguments "${@}"

sx::k8s::port_forward \
  "${query:-}" \
  "${namespace:-}" \
  "${all_namespaces:-false}" \
  "${random_port:-false}" \
  "${port:-}"
