#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/shell.sh"

##? Run a shell into a kubernetes node
##?
##? Notes:
##?   Highly influenced by https://github.com/kvaps/kubectl-node-shell
##?
##? Usage:
##?     shell [<query>] [--use-ssm]
##?
##? Options:
##?     --use-ssm  Use AWS SSM Agent to connect to instance
##?
##? Examples:
##?     shell
##?     shell ip-192-168-1-1.ec2.internal
##?     shell --use-ssm

sx::parse_arguments "${@}"

sx::k8s::shell "${query:-}" "${use_ssm:-false}"
