#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_CLI_DIR}/.library/tmux/core.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/tmux.sh"

##? Create a new TMUX window with the given pod details
##?
##? Usage:
##?     tmux [[<query>] [--namespace <name> | --all-namespaces] | --namespace <name> --pod <name> --container <name>]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -a --all-namespaces  All namespaces
##?     -p --pod <name>  The pod name
##?     -c --container <name>  The container name
##?
##? Examples:
##?     tmux
##?     tmux nginx
##?     tmux nginx --all-namespaces
##?     tmux --namespace nginx --pod nginx --container nginx
##?     tmux --namespace kube-system
##?     tmux --all-namespaces --previous

sx::parse_arguments "${@}"

sx::k8s::tmux \
  "${query:-}" \
  "${namespace:-}" \
  "${pod:-}" \
  "${container:-}" \
  "${all_namespaces:-false}"
