#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/trace.sh"

##? Traces status of services and deployments
##?
##? Usage:
##?     trace [<query>] [--namespace <name> | --all-namespaces]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -a --all-namespaces  All namespaces
##?
##? Examples:
##?     trace
##?     trace prometheus
##?     trace --namespace kube-system
##?     trace --all-namespaces

sx::parse_arguments "${@}"

sx::k8s::trace "${query:-}" "${namespace:-}" "${all_namespaces:-false}"
