- name: Detecting - iTerm is available
  stat:
    path: /Applications/iTerm.app
  register: iterm

- name: Installing iTerm application
  homebrew_cask:
    name: "iterm2"
    state: present
  register: new_iterm
  when:
    - not iterm.stat.exists

- name: Configuring iTerm to use custom preferences
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true
    state: present
  notify:
    - Restart iTerm
  when:
    - iterm.stat.exists or new_iterm is successful

- name: Configuring iTerm to load preferences from Sphynx directory
  osx_defaults:
    domain: com.googlecode.iterm2.plist
    key: PrefsCustomFolder
    type: string
    value: "{{ applications_settings_dir }}/osx/iterm"
    state: present
  notify:
    - Restart iTerm
  when:
    - iterm.stat.exists or new_iterm is successful

- name: Configuring iTerm settings file symlink
  file:
    src: "{{ applications_settings_dir }}/osx/iTerm/com.googlecode.iterm2.plist"
    dest: "{{ ansible_env.HOME }}/Library/Preferences/com.googlecode.iterm2.plist"
    state: link
    force: yes
  when:
    - not iterm.stat.exists or new_iterm is successful or (iterm.stat.islnk is defined and not iterm.stat.islnk)
