#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/run.sh"

##? Run OS-specific ansible playbook
##?
##? Usage:
##?     run
##?
##? Examples:
##?     run

sx::parse_arguments "${@}"

sx::playbook::run
