#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/run.sh"

##? Run OS-specific ansible playbook
##?
##? Usage:
##?     run
##?
##? Examples:
##?     run

if [ "${#}" -ne '0' ]; then
  sx::parse_arguments "${@}"
fi

sx::playbook::run
