#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_COMMAND_DIR}/system/core/clipboard.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/file.sh"

##? Share files via "transfer.sh"
##?
##? Usage:
##?     file <path>
##?
##? Examples:
##?     file ./test.txt

sx::parse_arguments "${@}"

sx::share::file "${path:-}"
