homebrew_repositories:
  - eddieantonio/eddieantonio
  - hashicorp/tap
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - homebrew/cask-drivers
  - teamookla/speedtest

homebrew_packages:
  - apktool
  - awscli
  - bash
  - bat
  - bench
  - binutils
  - coreutils
  - dex2jar
  - diffutils
  - duf
  - ed
  - ffmpeg
  - file-formula
  - findutils
  - { name: "fluxcd/tap/flux", installed_name: "flux" }
  - gawk
  - gcc
  - gh
  - git
  - git-delta
  - git-flow
  - git-lfs
  - gnu-indent
  - gnupg
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gnutls
  - { name: "golang", installed_name: "go" }
  - go-task
  - gpatch
  - gradle
  - grep
  - gzip
  - { name: "minamijoyo/hcledit/hcledit", installed_name: "hcledit" }
  - htop
  - hugo
  - hyperfine
  - hexyl
  - htmlq
  - icdiff
  - imgcat
  - jadx
  - jq
  - kcat
  - kind
  - kotlin
  - kubernetes-cli
  - krew
  - kubespy
  - less
  - m4
  - make
  - mas
  - maven
  - mongosh
  - navi
  - ncdu
  - nmap
  - node
  - nvm
  - openssh
  - pidcat
  - poetry
  - postgresql
  - pyenv
  - { name: "python", installed_name: "python@3.9" }
  - rsync
  - scrcpy
  - screen
  - shpotify
  - sipcalc
  - speedtest
  - sqlite
  - starship
  - stern
  - subnetcalc
  - telnet
  - {
      name: "mbode/tap/terraform-state-mover",
      installed_name: "terraform-state-mover",
    }
  - terragrunt
  - tfenv
  - the_silver_searcher
  - tmux
  - topgrade
  - translate-shell
  - tree
  - unzip
  - vault
  - vim
  - watch
  - wdiff
  - { name: "weaveworks/tap/eksctl", installed_name: "eksctl" }
  - wget
  - yq

homebrew_apps:
  - alacritty
  - appcleaner
  - bartender
  - caffeine
  - cleanshot
  - clipy
  - deckset
  - discord
  - github
  - google-chrome
  - google-cloud-sdk
  - grammarly
  - grammarly-desktop
  - { name: "hpedrorodrigues/tools/dockutil", installed_name: "dockutil" }
  - iina
  - istat-menus
  - jetbrains-toolbox
  - licecap
  - meld
  - monitorcontrol
  - obsidian
  - pdfelement
  - postman
  - rectangle
  - session-manager-plugin
  - skype
  - spotify
  - temurin8 # JDK 8
  - temurin11 # JDK 11
  - temurin17 # JDK 17
  - temurin21 # JDK 21
  - vagrant
  - virtualbox
  - wireshark
  - zoom
