- hosts: all
  connection: local

  roles:
    - role: apt
      become: true
    - linuxbrew
    - role: snap
      become: true
    - role: docker
      become: true
    - git
    - go
    - dotfiles
    - vscode
    - google-chrome
    - firefox-developer-edition
    - jetbrains-toolbox
    - scripts
