#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/configure-device.sh"

##? Configures the Android device to be connected via SSH
##?
##? Usage:
##?     configure-device
##?
##? Examples:
##?     configure-device

sx::parse_arguments "${@}"

sx::termux::configure-device
