#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNXC_DIR}/.internal/all.sh"
source "${SPHYNXC_DIR}/android/shared/shared.sh"
source "${SPHYNXN_DIR}/shared/shared.sh"
source "${SPHYNXN_DIR}/core/new-session.sh"

##? Starts a new SSH session using the available device
##?
##? Usage:
##?     new-session [--ip <address>]
##?
##? Options:
##?     --ip <address>  The IP to be used to connect to
##?
##? Examples:
##?     new-session
##?     new-session --ip 192.168.0.2

sx::parse_arguments "${@}"

sx::termux::new-session "${ip:-}"
