#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_COMMAND_DIR}/.internal/all.sh"
source "${SPHYNX_COMMAND_DIR}/android/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/new-session.sh"

##? Starts a new SSH session using the available device
##?
##? Usage:
##?     new-session [--ip <address>]
##?
##? Options:
##?     --ip <address>  The IP to be used to connect to
##?
##? Examples:
##?     new-session
##?     new-session --ip 192.168.0.2

sx::parse_arguments "${@}"

sx::termux::new-session "${ip:-}"
