#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/dns.sh"

##? DNS utility functions
##?
##? Usage:
##?     dns (<address> | --flush)
##?
##? Options:
##?     --flush  Clear the DNS cache "Root access required"
##?
##? Examples:
##?     dns --flush
##?     dns github.com

sx::parse_arguments "${@}"

if ${flush:-false}; then
  sx::system::flush_cache
elif [ -n "${address:-}" ]; then
  sx::system::resolve_address "${address}"
else
  sx::error::illegal_arguments "${*}"
fi
