#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/debug.sh"

##? Debug cluster resources using interactive ephemeral containers
##?
##? Usage:
##?     debug [[<query>] [--namespace <name> | --all-namespaces] | --namespace <name> --pod <name> --container <name>] --image <image>
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -a --all-namespaces  All namespaces
##?     -p --pod <name>  The pod name
##?     -c --container <name>  The container name
##?     --image <image>  Container image to use for debug container.
##?
##? Examples:
##?     debug --image busybox
##?     debug keycloak --image busybox
##?     debug --image busybox --all-namespaces

sx::parse_arguments "${@}"

sx::k8s::debug \
  "${query:-}" \
  "${namespace:-}" \
  "${pod:-}" \
  "${container:-}" \
  "${image:-}" \
  "${all_namespaces:-false}"
