#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/describe.sh"

##? Show details of a specific resource
##?
##? Usage:
##?     describe [<query>] [--selector <selector>] [--namespace <name> | --all-namespaces] [--context <name>]
##?
##? Options:
##?     -l --selector <selector>  Selector (label query) to filter on
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     describe
##?     describe prometheus
##?     describe --selector app=prometheus
##?     describe --namespace kube-system
##?     describe --all-namespaces
##?     describe prometheus --context staging

sx::parse_arguments "${@}"

sx::k8s::describe "${query:-}" "${namespace:-}" "${all_namespaces:-false}" "${context:-}" "${selector:-}"
