#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/edit.sh"

##? Edit a resource using the default editor
##?
##? Usage:
##?     edit [<query>] [--namespace <name> | --all-namespaces] [--context <name>]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     edit
##?     edit state-metrics
##?     edit --namespace kube-system
##?     edit --all-namespaces
##?     edit state-metrics --context staging

sx::parse_arguments "${@}"

sx::k8s::edit "${query:-}" "${namespace:-}" "${all_namespaces:-false}" "${context:-}"
