#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/exec.sh"

##? Execute custom commands in a container
##?
##? Usage:
##?     exec [<query>] [-l <selector>] [--namespace <name> | --all-namespaces] [--command <command>] [--context <name>]
##?     exec --namespace <name> --pod <name> --container <name> [--command <command>] [--context <name>]
##?
##? Options:
##?     -l --selector <selector>  Selector (label query) to filter on
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -p --pod <name>  The pod name
##?     -c --container <name>  The container name
##?     --command <command>  Command to execute in the container
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     exec
##?     exec echo-server
##?     exec echo-server --all-namespaces
##?     exec --selector app=myapp
##?     exec --namespace echo-server --pod echo-server --container echo-server
##?     exec --namespace kube-system
##?     exec --all-namespaces
##?     exec echo-server --context staging

sx::parse_arguments "${@}"

sx::k8s::exec \
  "${query:-}" \
  "${selector:-}" \
  "${namespace:-}" \
  "${pod:-}" \
  "${container:-}" \
  "${command:-}" \
  "${all_namespaces:-false}" \
  "${context:-}"
