#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/logs.sh"

##? Print the logs for a container in a pod
##?
##? Usage:
##?     logs [<query>] [-l <selector>] [--namespace <name> | --all-namespaces] [--previous] [--context <name>]
##?     logs --namespace <name> --pod <name> --container <name> [--previous] [--context <name>]
##?
##? Options:
##?     -l --selector <selector>  Selector (label query) to filter on
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -p --pod <name>  The pod name
##?     -c --container <name>  The container name
##?     --previous  Print the logs for the previous instance of the container in a pod if it exists
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     logs
##?     logs kafka
##?     logs kafka --all-namespaces
##?     logs --selector app=kafka
##?     logs --namespace kafka --pod kafka --container kafka
##?     logs --namespace kube-system
##?     logs --all-namespaces --previous
##?     logs kafka --context staging

sx::parse_arguments "${@}"

sx::k8s::logs \
  "${query:-}" \
  "${selector:-}" \
  "${namespace:-}" \
  "${pod:-}" \
  "${container:-}" \
  "${all_namespaces:-false}" \
  "${previous:-false}" \
  "${context:-}"
