#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/ls.sh"

##? Print one or many resources
##?
##? Usage:
##?     ls [--namespace <name> | --all-namespaces] [--show-labels --output <format>] [--context <name>]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  List the resources across all namespaces
##?     -l --show-labels  Show all labels as the last column
##?     -o --output=(default | name | wide)  The output format [default: default]
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     ls --namespace kube-system
##?     ls --all-namespaces
##?     ls --show-labels
##?     ls --context staging

sx::parse_arguments "${@}"

sx::k8s::list::resources \
  "${namespace:-}" \
  "${output:-default}" \
  "${all_namespaces:-false}" \
  "${show_labels:-false}" \
  "${context:-}"
