#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/prof.sh"

##? Profile applications running in Kubernetes pods using `josepdcs/kubectl-prof`
##?
##? Usage:
##?     prof [<query>] [--selector <selector>] [--namespace <name> | --all-namespaces] [--timeout <duration>] [--non-root] [--keep-jobs] [--image <image>] [--context <name>] [-- <flags>...]
##?     prof --namespace <name> --pod <name> --container <name> [--timeout <duration>] [--non-root] [--keep-jobs] [--image <image>] [--context <name>] [-- <flags>...]
##?     prof --cleanup [--namespace <name> | --all-namespaces] [--context <name>]
##?
##? Options:
##?     -l --selector <selector>  Selector (label query) to filter on
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -p --pod <name>  The pod name
##?     -c --container <name>  The container name
##?     --timeout <duration>  Max wall-clock time for the whole profiling run, e.g. 30s, 5m, 1h [default: 10m]
##?     --non-root  Make the profiler shared dir writable for non-root targets (uses a privileged ephemeral debug container)
##?     --keep-jobs  Keep orphaned profiling jobs on failure for inspection
##?     --image <image>  Container image for the debug container used by --non-root [default: ghcr.io/hpedrorodrigues/debug]
##?     --cleanup  Delete all profiling jobs created by kubectl-prof
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     prof -- --lang java --time 1m
##?     prof --non-root -- -l java -t 1m
##?     prof --timeout 30m -- -l java -t 20m
##?     prof workspaces-events --namespace staging -- -l java -t 1m -o flamegraph
##?     prof --namespace staging --pod my-pod --container my-container -- -l go -t 30s
##?     prof -- -l python -t 5m -o speedscope --local-path /tmp
##?     prof piper-ai-executor -n prod --non-root -- -l java -t 30s --log-level trace
##?     prof --cleanup --namespace staging
##?     prof kafka --context staging -- -l java -t 1m

sx::parse_arguments "${@}"

if ${cleanup:-false}; then
  sx::k8s::prof::cleanup "${namespace:-}" "${all_namespaces:-false}" "${context:-}"
else
  sx::k8s::prof \
    "${query:-}" \
    "${selector:-}" \
    "${namespace:-}" \
    "${pod:-}" \
    "${container:-}" \
    "${all_namespaces:-false}" \
    "${non_root:-false}" \
    "${keep_jobs:-false}" \
    "${timeout:-10m}" \
    "${image:-}" \
    "${flags[*]:-}" \
    "${context:-}"
fi
