#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/resource-summary.sh"

##? Print a resource summary for pods or nodes
##?
##? Usage:
##?     resource-summary (pods [<query>] [--namespace <name> | --all-namespaces] [--selector <query>] | nodes [<query>]) [--watch] [--interval <seconds>] [--context <name>]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -l --selector <query>  Selector (label query) to filter on
##?     -w --watch  Watch the resource summary continuously
##?     -i --interval <seconds>  Refresh interval in seconds [default: 2]
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     resource-summary
##?     resource-summary pods --watch
##?     resource-summary nodes --watch --interval 5
##?     resource-summary pods --context staging

sx::parse_arguments "${@}"

if ${watch:-false}; then
  sx::k8s::resource_summary::watch \
    "${interval:-2}" \
    "${pods:-false}" \
    "${query:-}" \
    "${namespace:-}" \
    "${all_namespaces:-false}" \
    "${selector:-}" \
    "${context:-}"
elif ${pods:-false}; then
  sx::k8s::pods::resource_summary "${query:-}" "${namespace:-}" "${all_namespaces:-false}" "${selector:-}" "${context:-}"
elif ${nodes:-false}; then
  sx::k8s::nodes::resource_summary "${query:-}" "${context:-}"
else
  sx::error::illegal_arguments "${*}"
fi
