#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/resource-summary.sh"

##? Print a resource summary for pods or nodes
##?
##? Usage:
##?     resource-summary (pods [<query>] [--namespace <name> | --all-namespaces] [--selector <query>] | nodes [<query>])
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -l --selector <query>  Selector (label query) to filter on
##?
##? Examples:
##?     resource-summary

sx::parse_arguments "${@}"

if ${pods:-false}; then
  sx::k8s::pods::resource_summary "${query:-}" "${namespace:-}" "${all_namespaces:-false}" "${selector:-}"
elif ${nodes:-false}; then
  sx::k8s::nodes::resource_summary "${query:-}"
else
  sx::error::illegal_arguments "${*}"
fi
