#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/secret.sh"

##? Inspect and decode secrets
##?
##? Usage:
##?     secret [<query> | --list | --exact <name>] [--namespace <name> | --all-namespaces] [--key <key>]
##?
##? Options:
##?     -l --list  Print all secrets without selecting one
##?     -e --exact <name>  Name to be used without checking for it
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -k --key <key>  Print only the decoded value of this key
##?
##? Examples:
##?     secret
##?     secret database
##?     secret database --key password
##?     secret --exact database-credentials --key password
##?     secret --list --namespace kube-system
##?     secret --list --all-namespaces

sx::parse_arguments "${@}"

sx::k8s::secret \
  "${query:-}" \
  "${exact:-}" \
  "${namespace:-}" \
  "${all_namespaces:-false}" \
  "${list:-false}" \
  "${key:-}"
