#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/secret.sh"

##? Inspect and decode secrets
##?
##? Usage:
##?     secret [<query>] [--selector <selector>] [--namespace <name> | --all-namespaces] [--key <key>] [--context <name>]
##?     secret --list [--selector <selector>] [--namespace <name> | --all-namespaces] [--key <key>] [--context <name>]
##?     secret --exact <name> [--namespace <name> | --all-namespaces] [--key <key>] [--context <name>]
##?
##? Options:
##?     -l --list  Print all secrets without selecting one
##?     --selector <selector>  Selector (label query) to filter on
##?     -e --exact <name>  Name to be used without checking for it
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  All namespaces
##?     -k --key <key>  Print only the decoded value of this key
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     secret
##?     secret database
##?     secret --selector app=database
##?     secret database --key password
##?     secret --exact database-credentials --key password
##?     secret --list --namespace kube-system
##?     secret --list --all-namespaces
##?     secret database --context staging

sx::parse_arguments "${@}"

sx::k8s::secret \
  "${query:-}" \
  "${exact:-}" \
  "${namespace:-}" \
  "${all_namespaces:-false}" \
  "${list:-false}" \
  "${key:-}" \
  "${context:-}" \
  "${selector:-}"
