#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source "${SPHYNX_CLI_DIR}/.internal/all.sh"
source "${SPHYNX_NAMESPACE_DIR}/shared/shared.sh"
source "${SPHYNX_NAMESPACE_DIR}/core/topology.sh"

##? Show K8S pods distribution throughout the cluster
##?
##? Usage:
##?     topology [<query>] [--selector <selector>] [--resources] [--show-labels] [--namespace <name> | --all-namespaces] [--context <name>]
##?
##? Options:
##?     -n --namespace <name>  The namespace scope for requests
##?     -A --all-namespaces  Run this command considering all pods of all namespaces
##?     -r --resources  Run this command considering resource usage
##?     --show-labels  Show instance labels
##?     -l --selector <selector>  Selector (label query) to filter on
##?     --context <name>  The name of the kubeconfig context to use
##?
##? Examples:
##?     topology --namespace kube-system
##?     topology --all-namespaces
##?     topology --resources
##?     topology --show-labels
##?     topology --selector app=app
##?     topology --context staging

sx::parse_arguments "${@}"

sx::k8s::topology \
  "${query:-}" \
  "${selector:-}" \
  "${all_namespaces:-false}" \
  "${resources:-false}" \
  "${show_labels:-false}" \
  "${context:-}" \
  "${namespace:-}"
