- name: Updating Pip
  pip:
    name: pip
    state: latest
  become: yes

- name: Getting all installed Pip packages
  command: "pip3 list"
  register: installed_packages
  check_mode: no
  changed_when: false

- name: Installing Pip packages
  become: true
  pip:
    name: "{{ pip_packages }}"
    state: present
  with_items: "{{ pip_packages }}"
  when:
    - pip_packages | count > 0
    - item not in installed_packages.stdout
