name: Checks (Pull Request)
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./sx lint
        shell: bash
  tests:
    name: Tests
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./sx test
        shell: bash
  build:
    name: Build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: arduino/setup-task@v1
      - run: task --taskfile=modules/images/Taskfile.yml build
        shell: bash
