name: Build and Push (Stable)
on:
  push:
    branches:
      - main
    paths:
      - "modules/images/**"
      - "!**.md"
jobs:
  build-and-push:
    name: Build & Push
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: arduino/setup-task@v1
      - run: task --taskfile=modules/images/Taskfile.yml build -- --push
        shell: bash
