name: Release Drafter
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: release-drafter
  cancel-in-progress: true
jobs:
  draft_release_notes:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
