name: Release Drafter
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  draft_release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
