name: Build and Push (Stable)
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
jobs:
  build-and-push:
    name: Build & Push
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - run: ./alien/alien --build-and-push
        shell: bash
