- name: Installing fonts
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/Library/Fonts/{{ item | basename }}"
  with_items:
    - "{{ lookup('fileglob', '{{ fonts_dir }}/firacode/otf/*.otf').split(',') }}"
